2024-07-08 15:03:39 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-08 15:04:28 - tracking.views - INFO - Sending email to 1chandailrc1@gmail.com. Process ID: 52663, Thread ID: 138477741573696
2024-07-08 15:04:38 - tracking.email_utils - INFO - email_utils.py: Email db entry created for 1chandailrc1@gmail.com at 2024-07-08 09:34:38.368157+00:00
2024-07-08 15:04:38 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to 1chandailrc1@gmail.com
2024-07-08 15:04:38 - tracking.views - INFO - Sending email to chandailrc@gmail.com. Process ID: 52663, Thread ID: 138477741573696
2024-07-08 15:04:48 - tracking.email_utils - INFO - email_utils.py: Email db entry created for chandailrc@gmail.com at 2024-07-08 09:34:48.558501+00:00
2024-07-08 15:04:48 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to chandailrc@gmail.com
2024-07-08 15:04:48 - tracking.views - INFO - Sending email to chandailrc@hotmail.com. Process ID: 52663, Thread ID: 138477741573696
2024-07-08 15:04:58 - tracking.email_utils - INFO - email_utils.py: Email db entry created for chandailrc@hotmail.com at 2024-07-08 09:34:58.741147+00:00
2024-07-08 15:04:58 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to chandailrc@hotmail.com
2024-07-08 15:04:58 - tracking.views - INFO - Sending email to singhal1959a@gmail.com. Process ID: 52663, Thread ID: 138477741573696
2024-07-08 15:05:08 - tracking.email_utils - INFO - email_utils.py: Email db entry created for singhal1959a@gmail.com at 2024-07-08 09:35:08.911913+00:00
2024-07-08 15:05:09 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to singhal1959a@gmail.com
2024-07-08 15:05:09 - tracking.views - INFO - Sending email to singhal24a@gmail.com. Process ID: 52663, Thread ID: 138477741573696
2024-07-08 15:05:19 - tracking.email_utils - INFO - email_utils.py: Email db entry created for singhal24a@gmail.com at 2024-07-08 09:35:19.104186+00:00
2024-07-08 15:05:19 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to singhal24a@gmail.com
2024-07-08 15:05:19 - tracking.views - INFO - Sending email to chandailrcsai@gmail.com. Process ID: 52663, Thread ID: 138477741573696
2024-07-08 15:05:29 - tracking.email_utils - INFO - email_utils.py: Email db entry created for chandailrcsai@gmail.com at 2024-07-08 09:35:29.302864+00:00
2024-07-08 15:05:29 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to chandailrcsai@gmail.com
2024-07-08 15:05:29 - tracking.views - INFO - Sending email to chandailrcsai@yahoo.com. Process ID: 52663, Thread ID: 138477741573696
2024-07-08 15:05:39 - tracking.email_utils - INFO - email_utils.py: Email db entry created for chandailrcsai@yahoo.com at 2024-07-08 09:35:39.467880+00:00
2024-07-08 15:05:39 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to chandailrcsai@yahoo.com
2024-07-08 15:05:39 - tracking.views - INFO - Sending email to chandailrcsai@aol.com. Process ID: 52663, Thread ID: 138477741573696
2024-07-08 15:05:49 - tracking.email_utils - INFO - email_utils.py: Email db entry created for chandailrcsai@aol.com at 2024-07-08 09:35:49.912182+00:00
2024-07-08 15:05:50 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to chandailrcsai@aol.com
2024-07-08 15:05:50 - tracking.views - INFO - Sending email to chandailrcsai@outlook.com. Process ID: 52663, Thread ID: 138477741573696
2024-07-08 15:06:00 - tracking.email_utils - INFO - email_utils.py: Email db entry created for chandailrcsai@outlook.com at 2024-07-08 09:36:00.109417+00:00
2024-07-08 15:06:00 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to chandailrcsai@outlook.com
2024-07-08 15:06:00 - tracking.views - INFO - Sending email to spamtestsai@outlook.com. Process ID: 52663, Thread ID: 138477741573696
2024-07-08 15:06:10 - tracking.email_utils - INFO - email_utils.py: Email db entry created for spamtestsai@outlook.com at 2024-07-08 09:36:10.335876+00:00
2024-07-08 15:06:10 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to spamtestsai@outlook.com
2024-07-08 15:06:10 - tracking.views - INFO - Sending email to 4x8wu32z@temporary-mail.net. Process ID: 52663, Thread ID: 138477741573696
2024-07-08 15:06:20 - tracking.email_utils - INFO - email_utils.py: Email db entry created for 4x8wu32z@temporary-mail.net at 2024-07-08 09:36:20.522761+00:00
2024-07-08 15:06:20 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to 4x8wu32z@temporary-mail.net
2024-07-08 15:06:20 - tracking.views - INFO - Sending email to tepanogudid@jollyfree.com. Process ID: 52663, Thread ID: 138477741573696
2024-07-08 15:06:30 - tracking.email_utils - INFO - email_utils.py: Email db entry created for tepanogudid@jollyfree.com at 2024-07-08 09:36:30.714309+00:00
2024-07-08 15:06:30 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to tepanogudid@jollyfree.com
2024-07-08 15:06:30 - tracking.views - INFO - Sending email to averey@eachence.com. Process ID: 52663, Thread ID: 138477741573696
2024-07-08 15:06:40 - tracking.email_utils - INFO - email_utils.py: Email db entry created for averey@eachence.com at 2024-07-08 09:36:40.875897+00:00
2024-07-08 15:06:40 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to averey@eachence.com
2024-07-08 15:06:40 - tracking.views - INFO - Sending email to lamoruze@pelagius.net. Process ID: 52663, Thread ID: 138477741573696
2024-07-08 15:06:51 - tracking.email_utils - INFO - email_utils.py: Email db entry created for lamoruze@pelagius.net at 2024-07-08 09:36:51.057452+00:00
2024-07-08 15:06:51 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to lamoruze@pelagius.net
2024-07-08 15:06:51 - tracking.views - INFO - Sending email to hqszmzse@flymail.tk. Process ID: 52663, Thread ID: 138477741573696
2024-07-08 15:07:01 - tracking.email_utils - INFO - email_utils.py: Email db entry created for hqszmzse@flymail.tk at 2024-07-08 09:37:01.295205+00:00
2024-07-08 15:07:01 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to hqszmzse@flymail.tk
2024-07-08 15:07:01 - tracking.views - INFO - Sending email to jixamo8511@carspure.com. Process ID: 52663, Thread ID: 138477741573696
2024-07-08 15:07:11 - tracking.email_utils - INFO - email_utils.py: Email db entry created for jixamo8511@carspure.com at 2024-07-08 09:37:11.389749+00:00
2024-07-08 15:07:11 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to jixamo8511@carspure.com
2024-07-08 15:07:11 - tracking.views - INFO - Sending email to spamtestersai@maildrop.cc. Process ID: 52663, Thread ID: 138477741573696
2024-07-08 15:07:21 - tracking.email_utils - INFO - email_utils.py: Email db entry created for spamtestersai@maildrop.cc at 2024-07-08 09:37:21.531835+00:00
2024-07-08 15:07:21 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to spamtestersai@maildrop.cc
2024-07-08 15:07:21 - tracking.views - INFO - Sending email to mtkzvf@vobau.net. Process ID: 52663, Thread ID: 138477741573696
2024-07-08 15:07:31 - tracking.email_utils - INFO - email_utils.py: Email db entry created for mtkzvf@vobau.net at 2024-07-08 09:37:31.687282+00:00
2024-07-08 15:07:31 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to mtkzvf@vobau.net
2024-07-08 15:07:31 - django.server - INFO - "POST /send-tracked-email/ HTTP/1.1" 200 2253
2024-07-08 15:07:32 - django.server - INFO - "GET /dashboard/ HTTP/1.1" 200 251258
2024-07-08 15:07:32 - tracking.urls - INFO - urls.py: PIXEL Request received for email 1chandailrc1@gmail.com from ip: 127.0.0.1
2024-07-08 15:07:32 - tracking.views - INFO - View2 called. Process ID: 52663, Thread ID: 138477741573696
2024-07-08 15:07:32 - tracking.views - INFO - views.py/handle_tracking: Current time: 2024-07-08 09:37:32.126707+00:00 | Mail sent: 2024-07-08 09:34:38.295437+00:00 | Difference: 0:02:53.831270
2024-07-08 15:07:32 - tracking.urls - INFO - urls.py: PIXEL Request received for email chandailrc@gmail.com from ip: 127.0.0.1
2024-07-08 15:07:32 - tracking.views - INFO - View2 called. Process ID: 52663, Thread ID: 138477741573696
2024-07-08 15:07:32 - tracking.views - INFO - views.py/handle_tracking: Current time: 2024-07-08 09:37:32.279086+00:00 | Mail sent: 2024-07-08 09:34:48.471402+00:00 | Difference: 0:02:43.807684
2024-07-09 14:33:07 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-09 14:33:44 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker/tracking/urls.py changed, reloading.
2024-07-09 14:33:44 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-09 14:34:00 - django.request - WARNING - Not Found: /serve_image
2024-07-09 14:34:00 - django.server - WARNING - "GET /serve_image HTTP/1.1" 404 3824
2024-07-09 14:34:29 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker/tracking/views.py changed, reloading.
2024-07-09 14:34:29 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-09 14:34:36 - django.request - WARNING - Not Found: /serve_image
2024-07-09 14:34:36 - django.server - WARNING - "GET /serve_image HTTP/1.1" 404 3824
2024-07-09 14:34:36 - django.request - WARNING - Not Found: /serve_image
2024-07-09 14:34:36 - django.server - WARNING - "GET /serve_image HTTP/1.1" 404 3824
2024-07-09 14:34:36 - django.request - WARNING - Not Found: /serve_image
2024-07-09 14:34:36 - django.server - WARNING - "GET /serve_image HTTP/1.1" 404 3824
2024-07-09 14:34:37 - django.request - WARNING - Not Found: /serve_image
2024-07-09 14:34:37 - django.server - WARNING - "GET /serve_image HTTP/1.1" 404 3824
2024-07-09 14:34:37 - django.request - WARNING - Not Found: /serve_image
2024-07-09 14:34:37 - django.server - WARNING - "GET /serve_image HTTP/1.1" 404 3824
2024-07-09 14:34:37 - django.request - WARNING - Not Found: /serve_image
2024-07-09 14:34:37 - django.server - WARNING - "GET /serve_image HTTP/1.1" 404 3824
2024-07-09 14:34:37 - django.request - WARNING - Not Found: /serve_image
2024-07-09 14:34:37 - django.server - WARNING - "GET /serve_image HTTP/1.1" 404 3824
2024-07-09 14:34:37 - django.request - WARNING - Not Found: /serve_image
2024-07-09 14:34:37 - django.server - WARNING - "GET /serve_image HTTP/1.1" 404 3824
2024-07-09 14:34:46 - django.server - INFO - "GET /serve-image HTTP/1.1" 301 0
2024-07-09 14:34:46 - django.request - ERROR - Internal Server Error: /serve-image/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/tracker/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/tracker/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker/tracking/views.py", line 171, in serve_image
    with open(image_path, 'rb') as image_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker/static/image/transparent.png'
2024-07-09 14:34:46 - django.server - ERROR - "GET /serve-image/ HTTP/1.1" 500 72545
2024-07-09 14:34:52 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker/tracking/views.py changed, reloading.
2024-07-09 14:34:52 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-09 14:34:54 - django.request - ERROR - Internal Server Error: /serve-image/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/tracker/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/tracker/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker/tracking/views.py", line 171, in serve_image
    with open(image_path, 'rb') as image_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker/static/transparent.png'
2024-07-09 14:34:54 - django.server - ERROR - "GET /serve-image/ HTTP/1.1" 500 72502
2024-07-09 14:34:55 - django.request - ERROR - Internal Server Error: /serve-image/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/tracker/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/tracker/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker/tracking/views.py", line 171, in serve_image
    with open(image_path, 'rb') as image_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker/static/transparent.png'
2024-07-09 14:34:55 - django.server - ERROR - "GET /serve-image/ HTTP/1.1" 500 72502
2024-07-09 14:34:56 - django.request - ERROR - Internal Server Error: /serve-image/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/tracker/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/tracker/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker/tracking/views.py", line 171, in serve_image
    with open(image_path, 'rb') as image_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker/static/transparent.png'
2024-07-09 14:34:56 - django.server - ERROR - "GET /serve-image/ HTTP/1.1" 500 72502
2024-07-09 14:34:56 - django.request - ERROR - Internal Server Error: /serve-image/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/tracker/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/tracker/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker/tracking/views.py", line 171, in serve_image
    with open(image_path, 'rb') as image_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker/static/transparent.png'
2024-07-09 14:34:56 - django.server - ERROR - "GET /serve-image/ HTTP/1.1" 500 72502
2024-07-09 14:34:56 - django.request - ERROR - Internal Server Error: /serve-image/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/tracker/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/tracker/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker/tracking/views.py", line 171, in serve_image
    with open(image_path, 'rb') as image_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker/static/transparent.png'
2024-07-09 14:34:56 - django.server - ERROR - "GET /serve-image/ HTTP/1.1" 500 72502
2024-07-09 14:34:56 - django.request - ERROR - Internal Server Error: /serve-image/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/tracker/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/tracker/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker/tracking/views.py", line 171, in serve_image
    with open(image_path, 'rb') as image_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker/static/transparent.png'
2024-07-09 14:34:56 - django.server - ERROR - "GET /serve-image/ HTTP/1.1" 500 72502
2024-07-09 14:34:56 - django.request - ERROR - Internal Server Error: /serve-image/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/tracker/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/tracker/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker/tracking/views.py", line 171, in serve_image
    with open(image_path, 'rb') as image_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker/static/transparent.png'
2024-07-09 14:34:56 - django.server - ERROR - "GET /serve-image/ HTTP/1.1" 500 72502
2024-07-09 14:34:57 - django.request - ERROR - Internal Server Error: /serve-image/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/tracker/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/tracker/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker/tracking/views.py", line 171, in serve_image
    with open(image_path, 'rb') as image_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker/static/transparent.png'
2024-07-09 14:34:57 - django.server - ERROR - "GET /serve-image/ HTTP/1.1" 500 72502
2024-07-09 14:34:57 - django.request - ERROR - Internal Server Error: /serve-image/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/tracker/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/tracker/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker/tracking/views.py", line 171, in serve_image
    with open(image_path, 'rb') as image_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker/static/transparent.png'
2024-07-09 14:34:57 - django.server - ERROR - "GET /serve-image/ HTTP/1.1" 500 72502
2024-07-09 14:35:22 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker/tracking/views.py changed, reloading.
2024-07-09 14:35:22 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-09 14:35:27 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker/tracking/views.py changed, reloading.
2024-07-09 14:35:27 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-09 14:35:29 - django.server - ERROR - "GET /serve-image/ HTTP/1.1" 500 59
2024-07-09 14:38:02 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker/tracking/views.py changed, reloading.
2024-07-09 14:38:02 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-09 14:38:08 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker/tracking/views.py changed, reloading.
2024-07-09 14:38:08 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-09 14:38:20 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker/tracking/views.py changed, reloading.
2024-07-09 14:38:20 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-09 14:38:27 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker/tracking/views.py changed, reloading.
2024-07-09 14:38:27 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-09 14:38:39 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker/tracking/urls.py changed, reloading.
2024-07-09 14:38:40 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-09 14:38:45 - django.request - WARNING - Not Found: /serve-image/
2024-07-09 14:38:45 - django.server - WARNING - "GET /serve-image/ HTTP/1.1" 404 3821
2024-07-09 14:38:50 - django.server - ERROR - "GET /image/ HTTP/1.1" 500 59
2024-07-09 14:40:27 - django.server - ERROR - "GET /image/ HTTP/1.1" 500 59
2024-07-09 14:41:29 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker/tracking/views.py changed, reloading.
2024-07-09 14:41:29 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-09 14:41:40 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker/tracking/views.py changed, reloading.
2024-07-09 14:41:40 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-09 14:41:45 - django.server - INFO - "GET /image/ HTTP/1.1" 200 95
2024-07-09 14:42:35 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker/tracking/views.py changed, reloading.
2024-07-09 14:42:36 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-09 14:42:39 - django.server - INFO - "GET /image/ HTTP/1.1" 200 95
2024-07-09 14:42:55 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker/tracking/views.py changed, reloading.
2024-07-09 14:42:55 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-09 14:43:11 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker/tracking/urls.py changed, reloading.
2024-07-09 14:43:11 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-09 15:32:33 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-09 15:33:23 - django.server - INFO - "GET /send-tracked-email/ HTTP/1.1" 200 2174
2024-07-09 15:33:23 - django.request - WARNING - Not Found: /favicon.ico
2024-07-09 15:33:26 - django.server - INFO - "GET /dashboard/ HTTP/1.1" 200 252570
2024-07-09 15:33:26 - django.request - WARNING - Not Found: /favicon.ico
2024-07-09 15:33:34 - tracking.views - INFO - Sending email to test@test.com. Process ID: 83051, Thread ID: 129525456062016
2024-07-09 15:33:45 - tracking.email_utils - INFO - email_utils.py: Email db entry created for test@test.com at 2024-07-09 10:03:45.037951+00:00
2024-07-09 15:33:45 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to test@test.com
2024-07-09 15:33:45 - django.server - INFO - "POST /send-tracked-email/ HTTP/1.1" 200 2252
2024-07-09 15:33:45 - django.request - WARNING - Not Found: /favicon.ico
2024-07-09 15:33:52 - tracking.urls - INFO - urls.py: PIXEL Request received for email test@test.com from ip: 127.0.0.1
2024-07-09 15:33:52 - tracking.views - INFO - View2 called. Process ID: 83051, Thread ID: 129525456062016
2024-07-09 15:33:52 - tracking.views - INFO - views.py/handle_tracking: Current time: 2024-07-09 10:03:52.195691+00:00 | Mail sent: 2024-07-09 10:03:44.974250+00:00 | Difference: 0:00:07.221441
2024-07-09 15:33:52 - django.server - INFO - "GET /track/0856d82a205144cd8ba67633047342f5/pixel.png HTTP/1.1" 200 67
2024-07-09 15:33:56 - django.server - INFO - "GET /dashboard/ HTTP/1.1" 200 253743
2024-07-09 15:34:15 - django.server - INFO - "GET /compose/ HTTP/1.1" 200 2174
2024-07-09 15:34:15 - django.request - WARNING - Not Found: /favicon.ico
2024-07-09 17:19:42 - django.request - WARNING - Not Found: /
2024-07-09 17:19:43 - django.request - WARNING - Not Found: /favicon.ico
2024-07-09 17:19:56 - django.request - ERROR - Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "tracking_email" does not exist
LINE 1: ...ng_email"."body", "tracking_email"."sent_at" FROM "tracking_...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
  File "/home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py", line 212, in dashboard
    return render(request, 'dashboard.html', {'emails': emails, 'unsubscribed_emails': unsubscribed_users})
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/defaulttags.py", line 198, in render
    len_values = len(values)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "tracking_email" does not exist
LINE 1: ...ng_email"."body", "tracking_email"."sent_at" FROM "tracking_...
                                                             ^

2024-07-09 19:04:12 - django.request - WARNING - Not Found: /favicon.ico
2024-07-09 20:19:56 - tracking.views - INFO - Sending email to 1chandairlc1@gmail.com. Process ID: 12978, Thread ID: 136044989118016
2024-07-09 20:20:06 - tracking.email_utils - INFO - email_utils.py: Email db entry created for 1chandairlc1@gmail.com at 2024-07-09 14:50:06.120298+00:00
2024-07-09 20:20:06 - tracking.email_utils - ERROR - email_utils.py: Error sending email to 1chandairlc1@gmail.com: [Errno 111] Connection refused
2024-07-09 20:22:05 - tracking.views - INFO - Sending email to 1chandairlc1@gmail.com. Process ID: 41559, Thread ID: 128188309042752
2024-07-09 20:22:15 - tracking.email_utils - INFO - email_utils.py: Email db entry created for 1chandairlc1@gmail.com at 2024-07-09 14:52:15.983360+00:00
2024-07-09 20:22:22 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to 1chandairlc1@gmail.com
2024-07-09 21:12:58 - tracking.views - INFO - Sending email to 1chandailrc1@gmail.com. Process ID: 49502, Thread ID: 136248683394624
2024-07-09 21:13:08 - tracking.email_utils - INFO - email_utils.py: Email db entry created for 1chandailrc1@gmail.com at 2024-07-09 15:43:08.226009+00:00
2024-07-09 21:13:13 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to 1chandailrc1@gmail.com
2024-07-09 22:20:18 - django.request - ERROR - Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 502, in parse
    compile_func = self.tags[command]
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
  File "/home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py", line 229, in dashboard
    return render(request, 'dashboard.html', {'emails': emails, 'unsubscribed_emails': unsubscribed_users})
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 196, in compile_nodelist
    return parser.parse()
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 565, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 77: 'endblock'. Did you forget to register or load this tag?
2024-07-09 22:24:13 - django.request - ERROR - Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 502, in parse
    compile_func = self.tags[command]
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
  File "/home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py", line 229, in dashboard
    return render(request, 'dashboard.html', {'emails': emails, 'unsubscribed_emails': unsubscribed_users})
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 196, in compile_nodelist
    return parser.parse()
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 565, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 77: 'endblock'. Did you forget to register or load this tag?
2024-07-09 22:25:06 - django.request - WARNING - Not Found: /empty-database/dashboard.html
2024-07-09 22:29:18 - django.request - WARNING - Not Found: /empty-database/dashboard.html
2024-07-09 22:29:22 - django.request - WARNING - Not Found: /empty-database/dashboard.html
2024-07-09 22:34:09 - django.request - WARNING - Not Found: /empty-database/dashboard.html
2024-07-09 22:39:38 - django.request - WARNING - Not Found: /empty-database/dashboard.html
2024-07-09 22:44:29 - django.request - WARNING - Not Found: /empty-database/dashboard.html
2024-07-09 22:47:47 - django.request - WARNING - Not Found: /empty-database/dashboard.html
2024-07-09 22:48:12 - django.request - ERROR - Internal Server Error: /empty-database/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 265, in _get_response_async
    self.check_response(response, callback)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view tracking.views.empty_database didn't return an HttpResponse object. It returned None instead.
2024-07-09 22:48:34 - django.request - WARNING - Not Found: /empty-database/dashboard.html
2024-07-09 22:50:47 - django.request - WARNING - Not Found: /empty-database/dashboard.html
2024-07-09 22:50:59 - django.request - WARNING - Not Found: /empty-database/dashboard.html
2024-07-09 22:51:04 - django.request - WARNING - Not Found: /dashboard.html
2024-07-09 22:51:07 - django.request - WARNING - Not Found: /dashboard.html
2024-07-11 09:48:12 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-11 09:51:25 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-11 09:54:18 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-11 09:55:13 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-11 09:55:14 - django.server - INFO - "GET /compose/ HTTP/1.1" 200 2174
2024-07-11 09:55:14 - django.request - WARNING - Not Found: /favicon.ico
2024-07-11 09:55:14 - django.server - WARNING - "GET /favicon.ico HTTP/1.1" 404 179
2024-07-11 09:55:43 - tracking.views - INFO - Sending email to test. Process ID: 15272, Thread ID: 138384433477184
2024-07-11 09:55:43 - tracking.email_utils - INFO - email_utils.py: Email db entry created for test at 2024-07-11 04:25:43.905801+00:00
2024-07-11 09:55:44 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to test
2024-07-11 09:55:44 - django.server - INFO - "POST /send-tracked-email/ HTTP/1.1" 200 2252
2024-07-11 09:55:44 - django.request - WARNING - Not Found: /favicon.ico
2024-07-11 09:55:46 - django.request - WARNING - Not Found: /static/images/logo.png
2024-07-11 09:55:46 - django.server - WARNING - "GET /static/images/logo.png HTTP/1.1" 404 179
2024-07-11 09:55:46 - tracking.urls - INFO - urls.py: PIXEL Request received for email test from ip: 127.0.0.1
2024-07-11 09:55:46 - tracking.views - INFO - View2 called. Process ID: 15272, Thread ID: 138384433477184
2024-07-11 09:55:46 - tracking.views - INFO - views.py/handle_tracking: PrefetchCheck - Current time: 2024-07-11 04:25:46.246604+00:00 | Mail sent: 2024-07-11 04:25:43.697785+00:00 | Difference: 0:00:02.548819
2024-07-11 09:55:46 - tracking.views - WARNING - views.py/handle_tracking: First request received for test with email_id 4 within 5 secs. Potential prefetching. Abandoning request!
2024-07-11 09:55:46 - django.request - WARNING - Not Found: /track/6a7d409f2dc34449851f073821bb15a9/pixel.png
2024-07-11 09:55:46 - django.server - WARNING - "GET /track/6a7d409f2dc34449851f073821bb15a9/pixel.png HTTP/1.1" 404 9
2024-07-11 09:57:39 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/urls.py changed, reloading.
2024-07-11 09:57:39 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-11 10:00:00 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-11 10:00:00 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-11 10:00:11 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-11 10:00:11 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-11 10:00:34 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/urls.py changed, reloading.
2024-07-11 10:00:34 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-11 10:01:08 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/email_utils.py changed, reloading.
2024-07-11 10:01:08 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-11 10:01:30 - tracking.views - INFO - Sending email to test. Process ID: 16537, Thread ID: 124458931058240
2024-07-11 10:01:30 - tracking.email_utils - INFO - email_utils.py: Email db entry created for test at 2024-07-11 04:31:30.736399+00:00
2024-07-11 10:01:30 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to test
2024-07-11 10:01:30 - django.server - INFO - "POST /send-tracked-email/ HTTP/1.1" 200 2252
2024-07-11 10:01:30 - django.request - WARNING - Not Found: /favicon.ico
2024-07-11 10:01:34 - django.request - WARNING - Not Found: /static/images/logo.png
2024-07-11 10:01:34 - django.server - WARNING - "GET /static/images/logo.png HTTP/1.1" 404 179
2024-07-11 10:01:34 - tracking.urls - INFO - urls.py: PIXEL Request received for email test from ip: 127.0.0.1
2024-07-11 10:01:34 - tracking.views - INFO - View2 called. Process ID: 16537, Thread ID: 124458931058240
2024-07-11 10:01:34 - tracking.views - INFO - views.py/handle_tracking: PrefetchCheck - Current time: 2024-07-11 04:31:34.913754+00:00 | Mail sent: 2024-07-11 04:31:30.711663+00:00 | Difference: 0:00:04.202091
2024-07-11 10:01:34 - tracking.views - WARNING - views.py/handle_tracking: First request received for test with email_id 5 within 5 secs. Potential prefetching. Abandoning request!
2024-07-11 10:01:34 - django.request - WARNING - Not Found: /track/50dd599bc14b4514a06636423c1b0ad1/pixel.png
2024-07-11 10:01:34 - django.server - WARNING - "GET /track/50dd599bc14b4514a06636423c1b0ad1/pixel.png HTTP/1.1" 404 9
2024-07-11 10:02:20 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/urls.py changed, reloading.
2024-07-11 10:02:21 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-11 10:03:11 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-11 10:03:11 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-11 10:03:46 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/urls.py changed, reloading.
2024-07-11 10:03:46 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-11 10:04:22 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/email_utils.py changed, reloading.
2024-07-11 10:04:22 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-11 10:04:50 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-11 10:04:50 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-11 10:05:10 - tracking.views - INFO - Sending email to test. Process ID: 17201, Thread ID: 123760245995072
2024-07-11 10:05:10 - tracking.email_utils - INFO - email_utils.py: Email db entry created for test at 2024-07-11 04:35:10.577902+00:00
2024-07-11 10:05:10 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to test
2024-07-11 10:05:10 - django.server - INFO - "POST /send-tracked-email/ HTTP/1.1" 200 2252
2024-07-11 10:05:13 - django.server - INFO - "GET /serve-image/logo.png HTTP/1.1" 301 0
2024-07-11 10:05:13 - tracking.urls - INFO - urls.py: PIXEL Request received for email test from ip: 127.0.0.1
2024-07-11 10:05:13 - tracking.views - INFO - View2 called. Process ID: 17201, Thread ID: 123760237602368
2024-07-11 10:05:13 - tracking.views - INFO - views.py/handle_tracking: PrefetchCheck - Current time: 2024-07-11 04:35:13.107279+00:00 | Mail sent: 2024-07-11 04:35:10.544870+00:00 | Difference: 0:00:02.562409
2024-07-11 10:05:13 - tracking.views - WARNING - views.py/handle_tracking: First request received for test with email_id 6 within 5 secs. Potential prefetching. Abandoning request!
2024-07-11 10:05:13 - django.request - WARNING - Not Found: /track/96ea3cc468fe4757bfae6f0f6146a1e0/pixel.png
2024-07-11 10:05:13 - django.server - WARNING - "GET /track/96ea3cc468fe4757bfae6f0f6146a1e0/pixel.png HTTP/1.1" 404 9
2024-07-11 10:05:13 - django.server - INFO - "GET /serve-image/logo.png/ HTTP/1.1" 200 7276
2024-07-11 10:08:05 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/email_utils.py changed, reloading.
2024-07-11 10:08:05 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-11 10:08:34 - tracking.views - INFO - Sending email to test. Process ID: 17937, Thread ID: 132469403678272
2024-07-11 10:08:34 - tracking.email_utils - INFO - email_utils.py: Email db entry created for test at 2024-07-11 04:38:34.431143+00:00
2024-07-11 10:08:34 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to test
2024-07-11 10:08:34 - django.server - INFO - "POST /send-tracked-email/ HTTP/1.1" 200 2252
2024-07-11 10:08:38 - tracking.urls - INFO - urls.py: PIXEL Request received for email test from ip: 127.0.0.1
2024-07-11 10:08:38 - tracking.views - INFO - View2 called. Process ID: 17937, Thread ID: 132469395285568
2024-07-11 10:08:38 - tracking.views - INFO - views.py/handle_tracking: PrefetchCheck - Current time: 2024-07-11 04:38:38.966116+00:00 | Mail sent: 2024-07-11 04:38:34.387845+00:00 | Difference: 0:00:04.578271
2024-07-11 10:08:38 - tracking.views - WARNING - views.py/handle_tracking: First request received for test with email_id 7 within 5 secs. Potential prefetching. Abandoning request!
2024-07-11 10:08:38 - django.request - WARNING - Not Found: /track/74a676c6783f43ef9e44ed3636af51ee/pixel.png
2024-07-11 10:08:38 - django.server - WARNING - "GET /track/74a676c6783f43ef9e44ed3636af51ee/pixel.png HTTP/1.1" 404 9
2024-07-11 10:08:38 - django.server - INFO - "GET /serve-image/logo.png/ HTTP/1.1" 200 7276
2024-07-11 10:13:02 - django.server - INFO - "GET /unsubscribed_users/ HTTP/1.1" 200 1257
2024-07-11 10:13:03 - django.server - INFO - "GET /dashboard/ HTTP/1.1" 200 3752
2024-07-11 10:15:11 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-11 10:15:12 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-11 10:15:31 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-11 10:15:31 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-11 10:17:33 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-11 10:17:33 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-11 10:17:50 - django.server - INFO - "GET /dashboard/ HTTP/1.1" 200 3752
2024-07-11 10:17:52 - django.request - ERROR - Internal Server Error: /unsubscribed_users/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py", line 208, in unsubscribed_users_list
    return render(request, 'unsubscribed_users_list.html', {'unsubscribed_emails': unsubscribed_users})
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/urls/resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'delete_unsubscribed_users' not found. 'delete_unsubscribed_users' is not a valid view function or pattern name.
2024-07-11 10:17:52 - django.server - ERROR - "GET /unsubscribed_users/ HTTP/1.1" 500 145
2024-07-11 10:18:43 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-11 10:18:43 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-11 10:18:44 - django.request - ERROR - Internal Server Error: /unsubscribed_users/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py", line 208, in unsubscribed_users_list
    return render(request, 'unsubscribed_users_list.html', {'unsubscribed_emails': unsubscribed_users})
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/urls/resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'delete_unsubscribed_users' not found. 'delete_unsubscribed_users' is not a valid view function or pattern name.
2024-07-11 10:18:44 - django.server - ERROR - "GET /unsubscribed_users/ HTTP/1.1" 500 145
2024-07-11 10:18:46 - django.server - INFO - "GET /dashboard/ HTTP/1.1" 200 3752
2024-07-11 10:18:47 - django.request - ERROR - Internal Server Error: /unsubscribed_users/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py", line 208, in unsubscribed_users_list
    return render(request, 'unsubscribed_users_list.html', {'unsubscribed_emails': unsubscribed_users})
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/urls/resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'delete_unsubscribed_users' not found. 'delete_unsubscribed_users' is not a valid view function or pattern name.
2024-07-11 10:18:47 - django.server - ERROR - "GET /unsubscribed_users/ HTTP/1.1" 500 145
2024-07-11 10:18:58 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-11 10:19:01 - django.request - ERROR - Internal Server Error: /unsubscribed_users/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py", line 208, in unsubscribed_users_list
    return render(request, 'unsubscribed_users_list.html', {'unsubscribed_emails': unsubscribed_users})
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/urls/resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'delete_unsubscribed_users' not found. 'delete_unsubscribed_users' is not a valid view function or pattern name.
2024-07-11 10:19:01 - django.server - ERROR - "GET /unsubscribed_users/ HTTP/1.1" 500 145
2024-07-11 10:19:06 - django.server - INFO - "GET /dashboard/ HTTP/1.1" 200 3752
2024-07-11 10:19:07 - django.server - INFO - "GET /dashboard/ HTTP/1.1" 200 3752
2024-07-11 10:19:10 - django.request - ERROR - Internal Server Error: /unsubscribed_users/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py", line 208, in unsubscribed_users_list
    return render(request, 'unsubscribed_users_list.html', {'unsubscribed_emails': unsubscribed_users})
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/template/defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/urls/resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'delete_unsubscribed_users' not found. 'delete_unsubscribed_users' is not a valid view function or pattern name.
2024-07-11 10:19:10 - django.server - ERROR - "GET /unsubscribed_users/ HTTP/1.1" 500 145
2024-07-11 10:19:46 - django.server - INFO - "GET /dashboard/ HTTP/1.1" 200 3752
2024-07-11 10:19:47 - django.server - INFO - "GET /unsubscribed_users/ HTTP/1.1" 200 1258
2024-07-11 10:20:47 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/urls.py changed, reloading.
2024-07-11 10:20:47 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-11 10:21:03 - django.server - INFO - "GET /unsubscribed_users/ HTTP/1.1" 200 1495
2024-07-11 10:21:14 - django.server - INFO - "GET /unsubscribe/?email=test HTTP/1.1" 200 439
2024-07-11 10:21:35 - django.server - INFO - "GET /dashboard/ HTTP/1.1" 200 3752
2024-07-11 10:21:54 - tracking.views - INFO - Sending email to test@test.com. Process ID: 20430, Thread ID: 133120716174912
2024-07-11 10:21:54 - tracking.email_utils - INFO - email_utils.py: Email db entry created for test@test.com at 2024-07-11 04:51:54.479995+00:00
2024-07-11 10:21:54 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to test@test.com
2024-07-11 10:21:54 - tracking.views - INFO - Sending email to one@one.com. Process ID: 20430, Thread ID: 133120716174912
2024-07-11 10:21:54 - tracking.email_utils - INFO - email_utils.py: Email db entry created for one@one.com at 2024-07-11 04:51:54.546714+00:00
2024-07-11 10:21:54 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to one@one.com
2024-07-11 10:21:54 - tracking.views - INFO - Sending email to two@two.com. Process ID: 20430, Thread ID: 133120716174912
2024-07-11 10:21:54 - tracking.email_utils - INFO - email_utils.py: Email db entry created for two@two.com at 2024-07-11 04:51:54.563464+00:00
2024-07-11 10:21:54 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to two@two.com
2024-07-11 10:21:54 - django.server - INFO - "POST /send-tracked-email/ HTTP/1.1" 200 2252
2024-07-11 10:21:59 - tracking.urls - INFO - urls.py: PIXEL Request received for email test@test.com from ip: 127.0.0.1
2024-07-11 10:21:59 - tracking.views - INFO - View2 called. Process ID: 20430, Thread ID: 133120632288832
2024-07-11 10:21:59 - tracking.views - INFO - views.py/handle_tracking: PrefetchCheck - Current time: 2024-07-11 04:51:59.831141+00:00 | Mail sent: 2024-07-11 04:51:54.449079+00:00 | Difference: 0:00:05.382062
2024-07-11 10:21:59 - django.server - INFO - "GET /serve-image/logo.png/ HTTP/1.1" 200 7276
2024-07-11 10:21:59 - django.server - INFO - "GET /track/3ffb744ae23a4335b9e8af4e5a894dc7/pixel.png HTTP/1.1" 200 67
2024-07-11 10:22:01 - django.server - INFO - "GET /unsubscribe/?email=test@test.com HTTP/1.1" 200 439
2024-07-11 10:22:05 - django.server - INFO - "POST /unsubscribe/?email=test@test.com HTTP/1.1" 200 27
2024-07-11 10:24:08 - django.server - INFO - "GET /unsubscribed_users/ HTTP/1.1" 200 1578
2024-07-11 10:24:11 - tracking.urls - INFO - urls.py: PIXEL Request received for email two@two.com from ip: 127.0.0.1
2024-07-11 10:24:11 - tracking.views - INFO - View2 called. Process ID: 20430, Thread ID: 133120632288832
2024-07-11 10:24:11 - tracking.views - INFO - views.py/handle_tracking: PrefetchCheck - Current time: 2024-07-11 04:54:11.756868+00:00 | Mail sent: 2024-07-11 04:51:54.557902+00:00 | Difference: 0:02:17.198966
2024-07-11 10:24:11 - django.server - INFO - "GET /serve-image/logo.png/ HTTP/1.1" 200 7276
2024-07-11 10:24:11 - django.server - INFO - "GET /track/558bdc3a5a8845749bb8296cda8749bb/pixel.png HTTP/1.1" 200 67
2024-07-11 10:24:13 - django.server - INFO - "GET /unsubscribe/?email=two@two.com HTTP/1.1" 200 439
2024-07-11 10:24:19 - django.server - INFO - "POST /unsubscribe/?email=two@two.com HTTP/1.1" 200 27
2024-07-11 10:24:22 - django.server - INFO - "GET /unsubscribed_users/ HTTP/1.1" 200 1659
2024-07-11 10:24:34 - django.server - INFO - "GET /dashboard/ HTTP/1.1" 200 6627
2024-07-11 10:24:42 - django.server - INFO - "GET /unsubscribed_users/ HTTP/1.1" 200 1659
2024-07-11 10:24:44 - django.server - INFO - "POST /delete-unsubscribed-users/ HTTP/1.1" 302 0
2024-07-11 10:24:44 - django.server - INFO - "GET /unsubscribed_users/ HTTP/1.1" 200 1495
2024-07-11 10:24:45 - django.server - INFO - "GET /dashboard/ HTTP/1.1" 200 6625
2024-07-11 10:24:46 - django.server - INFO - "GET /dashboard/ HTTP/1.1" 200 6625
2024-07-11 10:24:48 - django.server - INFO - "GET /dashboard/ HTTP/1.1" 200 6625
2024-07-11 10:26:34 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/email_tracker/settings.py changed, reloading.
2024-07-11 10:26:34 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-11 10:26:42 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/email_tracker/settings.py changed, reloading.
2024-07-11 10:26:43 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-11 10:40:41 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-11 10:40:41 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-11 10:41:27 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-11 10:41:27 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-11 10:41:43 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/email_tracker/settings.py changed, reloading.
2024-07-11 10:41:43 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-11 10:42:07 - tracking.views - INFO - Sending email to another@t.com. Process ID: 25019, Thread ID: 137823072024128
2024-07-11 10:42:07 - tracking.email_utils - INFO - email_utils.py: Email db entry created for another@t.com at 2024-07-11 05:12:07.058251+00:00
2024-07-11 10:42:07 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to another@t.com
2024-07-11 10:42:07 - django.server - INFO - "POST /send-tracked-email/ HTTP/1.1" 200 2252
2024-07-11 10:42:16 - tracking.urls - INFO - urls.py: PIXEL Request received for email another@t.com from ip: 127.0.0.1
2024-07-11 10:42:16 - tracking.views - INFO - View2 called. Process ID: 25019, Thread ID: 137823063631424
2024-07-11 10:42:16 - tracking.views - INFO - views.py/handle_tracking: PrefetchCheck - Current time: 2024-07-11 05:12:16.841199+00:00 | Mail sent: 2024-07-11 05:12:07.015337+00:00 | Difference: 0:00:09.825862
2024-07-11 10:42:16 - django.server - INFO - "GET /serve-image/logo.png/ HTTP/1.1" 200 7276
2024-07-11 10:42:16 - django.server - INFO - "GET /track/1346ecea596e4bb093e97c99a7f7f68a/pixel.png HTTP/1.1" 200 67
2024-07-11 10:46:37 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/email_tracker/settings.py changed, reloading.
2024-07-11 10:46:37 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-11 10:46:41 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/email_tracker/settings.py changed, reloading.
2024-07-11 10:46:41 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-11 12:42:35 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-11 12:42:36 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-11 12:43:26 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-11 12:43:26 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-11 14:20:04 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-11 14:20:04 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-11 14:20:08 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-11 14:20:08 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-11 14:26:42 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-11 14:26:43 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-11 14:26:56 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-11 14:26:56 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-11 14:48:14 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-11 14:48:14 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-11 15:46:07 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-11 15:46:07 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-13 13:27:03 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-13 13:27:17 - django.request - WARNING - Not Found: /favicon.ico
2024-07-13 13:27:21 - django.server - INFO - "GET /compose/ HTTP/1.1" 200 2174
2024-07-13 13:27:22 - django.server - INFO - "GET /compose/ HTTP/1.1" 200 2174
2024-07-13 13:27:23 - django.request - WARNING - Not Found: /favicon.ico
2024-07-13 13:27:50 - tracking.views - INFO - Sending email to 1chandailrc1@gmail.com. Process ID: 40574, Thread ID: 124392843507264
2024-07-13 13:27:50 - tracking.email_utils - INFO - email_utils.py: Email db entry created for 1chandailrc1@gmail.com at 2024-07-13 07:57:50.904709+00:00
2024-07-13 13:27:55 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to 1chandailrc1@gmail.com
2024-07-13 13:27:55 - django.server - INFO - "POST /send-tracked-email/ HTTP/1.1" 200 2252
2024-07-13 13:36:40 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/email_utils.py changed, reloading.
2024-07-13 13:36:41 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-13 13:37:22 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/email_utils.py changed, reloading.
2024-07-13 13:37:22 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-13 13:37:56 - tracking.views - INFO - Sending email to chandailrc@gmail.com. Process ID: 44254, Thread ID: 128316134651456
2024-07-13 13:37:56 - tracking.email_utils - INFO - email_utils.py: Email db entry created for chandailrc@gmail.com at 2024-07-13 08:07:56.531421+00:00
2024-07-13 13:38:01 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to chandailrc@gmail.com
2024-07-13 13:38:01 - django.server - INFO - "POST /send-tracked-email/ HTTP/1.1" 200 2252
2024-07-13 13:38:08 - django.server - INFO - "GET /dashboard/ HTTP/1.1" 200 8923
2024-07-13 14:24:35 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/email_tracker/settings.py changed, reloading.
2024-07-13 14:24:35 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-13 14:35:00 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-13 14:35:01 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-13 14:35:13 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-13 14:35:13 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-13 14:35:51 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/mailgun_utils.py changed, reloading.
2024-07-13 14:35:51 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-13 14:38:23 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-13 14:38:54 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-13 14:39:11 - django.server - INFO - "GET /send-mailgun-mail HTTP/1.1" 301 0
2024-07-13 14:39:12 - django.server - INFO - "GET /send-mailgun-mail/ HTTP/1.1" 200 38
2024-07-13 14:41:13 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/email_tracker/settings.py changed, reloading.
2024-07-13 14:42:20 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-13 14:42:32 - django.server - INFO - "GET /send-mailgun-mail/ HTTP/1.1" 200 24
2024-07-13 14:44:33 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-13 14:44:33 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-13 14:44:50 - django.server - INFO - "GET /send-mailgun-mail/ HTTP/1.1" 200 24
2024-07-13 14:44:50 - django.request - WARNING - Not Found: /favicon.ico
2024-07-13 16:09:51 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-13 16:09:52 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-13 16:16:36 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-13 16:16:36 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-13 16:17:24 - django.server - INFO - "GET /compose/ HTTP/1.1" 200 2174
2024-07-13 16:19:22 - tracking.views - INFO - Sending email to 1chandailrc1@gmail.com. Process ID: 73184, Thread ID: 127551099893312
2024-07-13 16:19:22 - tracking.email_utils - INFO - email_utils.py: Email db entry created for 1chandailrc1@gmail.com at 2024-07-13 10:49:22.722248+00:00
2024-07-13 16:19:27 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to 1chandailrc1@gmail.com
2024-07-13 16:19:27 - tracking.views - INFO - Sending email to chandailrc@gmail.com. Process ID: 73184, Thread ID: 127551099893312
2024-07-13 16:19:27 - tracking.email_utils - INFO - email_utils.py: Email db entry created for chandailrc@gmail.com at 2024-07-13 10:49:27.105876+00:00
2024-07-13 16:19:30 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to chandailrc@gmail.com
2024-07-13 16:19:30 - tracking.views - INFO - Sending email to chandailrc@hotmail.com. Process ID: 73184, Thread ID: 127551099893312
2024-07-13 16:19:30 - tracking.email_utils - INFO - email_utils.py: Email db entry created for chandailrc@hotmail.com at 2024-07-13 10:49:30.770870+00:00
2024-07-13 16:19:34 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to chandailrc@hotmail.com
2024-07-13 16:19:34 - tracking.views - INFO - Sending email to singhal1959a@gmail.com. Process ID: 73184, Thread ID: 127551099893312
2024-07-13 16:19:34 - tracking.email_utils - INFO - email_utils.py: Email db entry created for singhal1959a@gmail.com at 2024-07-13 10:49:34.946154+00:00
2024-07-13 16:19:39 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to singhal1959a@gmail.com
2024-07-13 16:19:39 - tracking.views - INFO - Sending email to singhal24a@gmail.com. Process ID: 73184, Thread ID: 127551099893312
2024-07-13 16:19:39 - tracking.email_utils - INFO - email_utils.py: Email db entry created for singhal24a@gmail.com at 2024-07-13 10:49:39.563468+00:00
2024-07-13 16:19:44 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to singhal24a@gmail.com
2024-07-13 16:19:44 - tracking.views - INFO - Sending email to chandailrcsai@gmail.com. Process ID: 73184, Thread ID: 127551099893312
2024-07-13 16:19:44 - tracking.email_utils - INFO - email_utils.py: Email db entry created for chandailrcsai@gmail.com at 2024-07-13 10:49:44.051304+00:00
2024-07-13 16:19:47 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to chandailrcsai@gmail.com
2024-07-13 16:19:47 - tracking.views - INFO - Sending email to chandailrcsai@outlook.com. Process ID: 73184, Thread ID: 127551099893312
2024-07-13 16:19:47 - tracking.email_utils - INFO - email_utils.py: Email db entry created for chandailrcsai@outlook.com at 2024-07-13 10:49:47.594182+00:00
2024-07-13 16:19:50 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to chandailrcsai@outlook.com
2024-07-13 16:19:50 - tracking.views - INFO - Sending email to spamtestsai@outlook.com. Process ID: 73184, Thread ID: 127551099893312
2024-07-13 16:19:50 - tracking.email_utils - INFO - email_utils.py: Email db entry created for spamtestsai@outlook.com at 2024-07-13 10:49:50.646704+00:00
2024-07-13 16:19:54 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to spamtestsai@outlook.com
2024-07-13 16:19:54 - tracking.views - INFO - Sending email to bucofomopudi@gotgel.org. Process ID: 73184, Thread ID: 127551099893312
2024-07-13 16:19:54 - tracking.email_utils - INFO - email_utils.py: Email db entry created for bucofomopudi@gotgel.org at 2024-07-13 10:49:54.305742+00:00
2024-07-13 16:19:58 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to bucofomopudi@gotgel.org
2024-07-13 16:19:58 - tracking.views - INFO - Sending email to lamoruze@pelagius.net. Process ID: 73184, Thread ID: 127551099893312
2024-07-13 16:19:58 - tracking.email_utils - INFO - email_utils.py: Email db entry created for lamoruze@pelagius.net at 2024-07-13 10:49:58.073831+00:00
2024-07-13 16:20:01 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to lamoruze@pelagius.net
2024-07-13 16:20:01 - tracking.views - INFO - Sending email to exodus4@imbetain.com. Process ID: 73184, Thread ID: 127551099893312
2024-07-13 16:20:01 - tracking.email_utils - INFO - email_utils.py: Email db entry created for exodus4@imbetain.com at 2024-07-13 10:50:01.872160+00:00
2024-07-13 16:20:06 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to exodus4@imbetain.com
2024-07-13 16:20:06 - tracking.views - INFO - Sending email to jd5gb0s7@flymail.tk. Process ID: 73184, Thread ID: 127551099893312
2024-07-13 16:20:06 - tracking.email_utils - INFO - email_utils.py: Email db entry created for jd5gb0s7@flymail.tk at 2024-07-13 10:50:06.225074+00:00
2024-07-13 16:20:10 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to jd5gb0s7@flymail.tk
2024-07-13 16:20:10 - tracking.views - INFO - Sending email to jixamo8511@carspure.com. Process ID: 73184, Thread ID: 127551099893312
2024-07-13 16:20:10 - tracking.email_utils - INFO - email_utils.py: Email db entry created for jixamo8511@carspure.com at 2024-07-13 10:50:10.267100+00:00
2024-07-13 16:20:14 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to jixamo8511@carspure.com
2024-07-13 16:20:14 - tracking.views - INFO - Sending email to spamtestersai@maildrop.cc. Process ID: 73184, Thread ID: 127551099893312
2024-07-13 16:20:14 - tracking.email_utils - INFO - email_utils.py: Email db entry created for spamtestersai@maildrop.cc at 2024-07-13 10:50:14.576345+00:00
2024-07-13 16:20:18 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to spamtestersai@maildrop.cc
2024-07-13 16:20:18 - tracking.views - INFO - Sending email to mtkzvf@vobau.net. Process ID: 73184, Thread ID: 127551099893312
2024-07-13 16:20:18 - tracking.email_utils - INFO - email_utils.py: Email db entry created for mtkzvf@vobau.net at 2024-07-13 10:50:18.666325+00:00
2024-07-13 16:20:22 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to mtkzvf@vobau.net
2024-07-13 16:20:22 - django.server - INFO - "POST /send-tracked-email/ HTTP/1.1" 200 2253
2024-07-13 17:00:56 - django.request - ERROR - Internal Server Error: /track-link/1/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:00:56 - django.server - ERROR - "GET /track-link/1/ HTTP/1.1" 500 145
2024-07-13 17:02:06 - django.request - ERROR - Internal Server Error: /track-link/1/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:02:06 - django.server - ERROR - "GET /track-link/1/ HTTP/1.1" 500 145
2024-07-13 17:02:54 - django.request - ERROR - Internal Server Error: /track-link/2/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:02:54 - django.server - ERROR - "GET /track-link/2/ HTTP/1.1" 500 145
2024-07-13 17:03:03 - django.request - ERROR - Internal Server Error: /track-link/2/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:03:03 - django.server - ERROR - "GET /track-link/2/ HTTP/1.1" 500 145
2024-07-13 17:03:05 - django.request - ERROR - Internal Server Error: /track-link/2/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:03:05 - django.server - ERROR - "GET /track-link/2/ HTTP/1.1" 500 145
2024-07-13 17:04:07 - django.request - ERROR - Internal Server Error: /track-link/3/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:04:07 - django.server - ERROR - "GET /track-link/3/ HTTP/1.1" 500 145
2024-07-13 17:04:07 - django.request - ERROR - Internal Server Error: /track-link/3/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:04:07 - django.server - ERROR - "GET /track-link/3/ HTTP/1.1" 500 145
2024-07-13 17:04:07 - django.request - ERROR - Internal Server Error: /track-link/3/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:04:07 - django.server - ERROR - "GET /track-link/3/ HTTP/1.1" 500 145
2024-07-13 17:04:07 - django.request - ERROR - Internal Server Error: /track-link/3/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:04:07 - django.server - ERROR - "GET /track-link/3/ HTTP/1.1" 500 145
2024-07-13 17:04:07 - django.request - ERROR - Internal Server Error: /track-link/3/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:04:07 - django.server - ERROR - "GET /track-link/3/ HTTP/1.1" 500 145
2024-07-13 17:04:42 - django.request - ERROR - Internal Server Error: /track-link/8/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:04:42 - django.server - ERROR - "GET /track-link/8/ HTTP/1.1" 500 145
2024-07-13 17:04:42 - django.request - WARNING - Not Found: /favicon.ico
2024-07-13 17:04:42 - django.server - WARNING - "GET /favicon.ico HTTP/1.1" 404 179
2024-07-13 17:04:44 - django.request - ERROR - Internal Server Error: /track-link/8/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:04:44 - django.server - ERROR - "GET /track-link/8/ HTTP/1.1" 500 145
2024-07-13 17:04:46 - django.request - ERROR - Internal Server Error: /track-link/8/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:04:46 - django.server - ERROR - "GET /track-link/8/ HTTP/1.1" 500 145
2024-07-13 17:04:47 - django.request - ERROR - Internal Server Error: /track-link/8/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:04:47 - django.server - ERROR - "GET /track-link/8/ HTTP/1.1" 500 145
2024-07-13 17:04:49 - django.request - ERROR - Internal Server Error: /track-link/8/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:04:49 - django.server - ERROR - "GET /track-link/8/ HTTP/1.1" 500 145
2024-07-13 17:06:11 - django.request - ERROR - Internal Server Error: /track-link/6/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:06:11 - django.server - ERROR - "GET /track-link/6/ HTTP/1.1" 500 145
2024-07-13 17:06:11 - django.request - WARNING - Not Found: /favicon.ico
2024-07-13 17:06:11 - django.server - WARNING - "GET /favicon.ico HTTP/1.1" 404 179
2024-07-13 17:06:12 - django.request - ERROR - Internal Server Error: /track-link/6/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:06:12 - django.server - ERROR - "GET /track-link/6/ HTTP/1.1" 500 145
2024-07-13 17:06:14 - django.request - ERROR - Internal Server Error: /track-link/6/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:06:14 - django.server - ERROR - "GET /track-link/6/ HTTP/1.1" 500 145
2024-07-13 17:06:15 - django.request - ERROR - Internal Server Error: /track-link/6/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:06:15 - django.server - ERROR - "GET /track-link/6/ HTTP/1.1" 500 145
2024-07-13 17:06:16 - django.request - ERROR - Internal Server Error: /track-link/6/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:06:16 - django.server - ERROR - "GET /track-link/6/ HTTP/1.1" 500 145
2024-07-13 17:06:31 - django.request - ERROR - Internal Server Error: /track-link/7/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:06:31 - django.server - ERROR - "GET /track-link/7/ HTTP/1.1" 500 145
2024-07-13 17:06:33 - django.request - ERROR - Internal Server Error: /track-link/7/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:06:33 - django.server - ERROR - "GET /track-link/7/ HTTP/1.1" 500 145
2024-07-13 17:06:35 - django.request - ERROR - Internal Server Error: /track-link/7/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:06:35 - django.server - ERROR - "GET /track-link/7/ HTTP/1.1" 500 145
2024-07-13 17:06:36 - django.request - ERROR - Internal Server Error: /track-link/7/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:06:36 - django.server - ERROR - "GET /track-link/7/ HTTP/1.1" 500 145
2024-07-13 17:06:38 - django.request - ERROR - Internal Server Error: /track-link/7/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:06:38 - django.server - ERROR - "GET /track-link/7/ HTTP/1.1" 500 145
2024-07-13 17:07:40 - django.request - ERROR - Internal Server Error: /track-link/6/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:07:40 - django.server - ERROR - "GET /track-link/6/ HTTP/1.1" 500 145
2024-07-13 17:08:25 - django.request - ERROR - Internal Server Error: /track-link/9/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:08:25 - django.server - ERROR - "GET /track-link/9/ HTTP/1.1" 500 145
2024-07-13 17:08:28 - django.request - ERROR - Internal Server Error: /track-link/9/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:08:28 - django.server - ERROR - "GET /track-link/9/ HTTP/1.1" 500 145
2024-07-13 17:08:29 - django.request - ERROR - Internal Server Error: /track-link/9/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:08:29 - django.server - ERROR - "GET /track-link/9/ HTTP/1.1" 500 145
2024-07-13 17:08:29 - django.request - ERROR - Internal Server Error: /track-link/9/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:08:29 - django.server - ERROR - "GET /track-link/9/ HTTP/1.1" 500 145
2024-07-13 17:08:30 - django.request - ERROR - Internal Server Error: /track-link/9/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:08:30 - django.server - ERROR - "GET /track-link/9/ HTTP/1.1" 500 145
2024-07-13 17:08:43 - django.request - ERROR - Internal Server Error: /track-link/11/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:08:43 - django.server - ERROR - "GET /track-link/11/ HTTP/1.1" 500 145
2024-07-13 17:08:44 - django.request - ERROR - Internal Server Error: /track-link/11/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:08:44 - django.server - ERROR - "GET /track-link/11/ HTTP/1.1" 500 145
2024-07-13 17:08:45 - django.request - ERROR - Internal Server Error: /track-link/11/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:08:45 - django.server - ERROR - "GET /track-link/11/ HTTP/1.1" 500 145
2024-07-13 17:08:46 - django.request - ERROR - Internal Server Error: /track-link/11/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:08:46 - django.server - ERROR - "GET /track-link/11/ HTTP/1.1" 500 145
2024-07-13 17:08:47 - django.request - ERROR - Internal Server Error: /track-link/11/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:08:47 - django.server - ERROR - "GET /track-link/11/ HTTP/1.1" 500 145
2024-07-13 17:09:47 - django.request - ERROR - Internal Server Error: /track-link/12/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:09:47 - django.server - ERROR - "GET /track-link/12/ HTTP/1.1" 500 145
2024-07-13 17:09:47 - django.request - ERROR - Internal Server Error: /track-link/12/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:09:47 - django.server - ERROR - "GET /track-link/12/ HTTP/1.1" 500 145
2024-07-13 17:09:48 - django.request - ERROR - Internal Server Error: /track-link/12/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:09:48 - django.server - ERROR - "GET /track-link/12/ HTTP/1.1" 500 145
2024-07-13 17:09:48 - django.request - ERROR - Internal Server Error: /track-link/12/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:09:48 - django.server - ERROR - "GET /track-link/12/ HTTP/1.1" 500 145
2024-07-13 17:09:49 - django.request - ERROR - Internal Server Error: /track-link/12/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:09:49 - django.server - ERROR - "GET /track-link/12/ HTTP/1.1" 500 145
2024-07-13 17:10:02 - django.request - ERROR - Internal Server Error: /track-link/13/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:10:02 - django.server - ERROR - "GET /track-link/13/ HTTP/1.1" 500 145
2024-07-13 17:10:02 - django.request - ERROR - Internal Server Error: /track-link/13/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:10:02 - django.server - ERROR - "GET /track-link/13/ HTTP/1.1" 500 145
2024-07-13 17:10:03 - django.request - ERROR - Internal Server Error: /track-link/13/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:10:03 - django.server - ERROR - "GET /track-link/13/ HTTP/1.1" 500 145
2024-07-13 17:10:03 - django.request - ERROR - Internal Server Error: /track-link/13/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:10:03 - django.server - ERROR - "GET /track-link/13/ HTTP/1.1" 500 145
2024-07-13 17:10:04 - django.request - ERROR - Internal Server Error: /track-link/13/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:10:04 - django.server - ERROR - "GET /track-link/13/ HTTP/1.1" 500 145
2024-07-13 17:10:43 - django.request - ERROR - Internal Server Error: /track-link/14/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:10:43 - django.server - ERROR - "GET /track-link/14/ HTTP/1.1" 500 145
2024-07-13 17:10:43 - django.request - ERROR - Internal Server Error: /track-link/14/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:10:43 - django.server - ERROR - "GET /track-link/14/ HTTP/1.1" 500 145
2024-07-13 17:10:44 - django.request - ERROR - Internal Server Error: /track-link/14/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:10:44 - django.server - ERROR - "GET /track-link/14/ HTTP/1.1" 500 145
2024-07-13 17:10:45 - django.request - ERROR - Internal Server Error: /track-link/14/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:10:45 - django.server - ERROR - "GET /track-link/14/ HTTP/1.1" 500 145
2024-07-13 17:10:45 - django.request - ERROR - Internal Server Error: /track-link/14/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:10:45 - django.server - ERROR - "GET /track-link/14/ HTTP/1.1" 500 145
2024-07-13 17:11:19 - django.request - ERROR - Internal Server Error: /track-link/15/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:11:19 - django.server - ERROR - "GET /track-link/15/ HTTP/1.1" 500 145
2024-07-13 17:11:23 - django.request - ERROR - Internal Server Error: /track-link/15/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:11:23 - django.server - ERROR - "GET /track-link/15/ HTTP/1.1" 500 145
2024-07-13 17:11:26 - django.request - ERROR - Internal Server Error: /track-link/15/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:11:26 - django.server - ERROR - "GET /track-link/15/ HTTP/1.1" 500 145
2024-07-13 17:11:29 - django.request - ERROR - Internal Server Error: /track-link/15/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:11:29 - django.server - ERROR - "GET /track-link/15/ HTTP/1.1" 500 145
2024-07-13 17:11:32 - django.request - ERROR - Internal Server Error: /track-link/15/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-13 17:11:32 - django.server - ERROR - "GET /track-link/15/ HTTP/1.1" 500 145
2024-07-14 10:29:37 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 10:34:44 - django.server - INFO - "GET /dashboard/ HTTP/1.1" 200 19597
2024-07-14 10:39:48 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-14 10:39:48 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 10:40:01 - django.server - INFO - "GET /send-mailgun-mail/ HTTP/1.1" 200 38
2024-07-14 10:40:25 - django.server - INFO - "GET /send-mailgun-mail/ HTTP/1.1" 200 38
2024-07-14 10:44:06 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/mailgun_utils.py changed, reloading.
2024-07-14 10:44:06 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 10:44:14 - django.server - INFO - "GET /send-mailgun-mail/ HTTP/1.1" 200 38
2024-07-14 10:44:41 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/mailgun_utils.py changed, reloading.
2024-07-14 10:44:41 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 10:44:53 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/mailgun_utils.py changed, reloading.
2024-07-14 10:44:53 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 10:44:57 - django.server - INFO - "GET /send-mailgun-mail/ HTTP/1.1" 200 24
2024-07-14 10:45:39 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/mailgun_utils.py changed, reloading.
2024-07-14 10:45:39 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 10:45:44 - django.server - INFO - "GET /send-mailgun-mail/ HTTP/1.1" 200 38
2024-07-14 10:51:06 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/mailgun_utils.py changed, reloading.
2024-07-14 10:51:06 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 10:51:19 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/mailgun_utils.py changed, reloading.
2024-07-14 10:51:20 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 10:51:34 - django.server - INFO - "GET /send-mailgun-mail/ HTTP/1.1" 200 38
2024-07-14 10:54:19 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-14 10:54:19 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 10:54:48 - django.server - INFO - "GET /send-mailgun-mail/ HTTP/1.1" 200 24
2024-07-14 11:50:46 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/mailgun_utils.py changed, reloading.
2024-07-14 11:50:47 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 11:50:57 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-14 11:50:57 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 11:52:00 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-14 11:52:00 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 11:52:15 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-14 11:52:15 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 11:52:23 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-14 11:52:24 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 11:52:48 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-14 11:52:48 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 11:52:54 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-14 11:52:54 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 11:53:31 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-14 11:53:31 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 11:53:35 - django.server - INFO - "GET /send-mailgun-mail/ HTTP/1.1" 200 38
2024-07-14 11:53:36 - django.request - WARNING - Not Found: /favicon.ico
2024-07-14 11:54:17 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/mailgun_utils.py changed, reloading.
2024-07-14 11:54:17 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 11:54:21 - django.server - INFO - "GET /send-mailgun-mail/ HTTP/1.1" 200 24
2024-07-14 11:54:21 - django.request - WARNING - Not Found: /favicon.ico
2024-07-14 11:57:25 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/mailgun_utils.py changed, reloading.
2024-07-14 11:57:25 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 11:57:43 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-14 11:57:43 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 11:57:52 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-14 11:57:52 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 11:58:07 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-14 11:58:07 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 11:58:44 - django.server - INFO - "GET /send-mailgun-mail/ HTTP/1.1" 200 24
2024-07-14 14:51:26 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-14 14:51:26 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 14:51:36 - django.server - INFO - "GET /send-mailgun-mail/ HTTP/1.1" 200 24
2024-07-14 15:02:22 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/email_utils.py changed, reloading.
2024-07-14 15:02:23 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 15:27:28 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 15:28:21 - tracking.views - INFO - Sending email to testing. Process ID: 68094, Thread ID: 137578913199680
2024-07-14 15:28:22 - tracking.email_utils - INFO - email_utils.py: Email db entry created for testing at 2024-07-14 09:58:22.242337+00:00
2024-07-14 15:28:22 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to testing
2024-07-14 15:28:22 - django.server - INFO - "POST /send-tracked-email/ HTTP/1.1" 200 2252
2024-07-14 15:28:22 - django.request - WARNING - Not Found: /favicon.ico
2024-07-14 15:28:25 - django.server - INFO - "GET /serve-image/logo.png HTTP/1.1" 301 0
2024-07-14 15:28:25 - tracking.urls - INFO - urls.py: PIXEL Request received for email testing from ip: 127.0.0.1
2024-07-14 15:28:25 - tracking.views - INFO - View2 called. Process ID: 68094, Thread ID: 137578913199680
2024-07-14 15:28:25 - tracking.views - INFO - views.py/handle_tracking: PrefetchCheck - Current time: 2024-07-14 09:58:25.066663+00:00 | Mail sent: 2024-07-14 09:58:21.937761+00:00 | Difference: 0:00:03.128902
2024-07-14 15:28:25 - tracking.views - WARNING - views.py/handle_tracking: First request received for testing with email_id 29 within 5 secs. Potential prefetching. Abandoning request!
2024-07-14 15:28:25 - django.request - WARNING - Not Found: /track/7e8d1d0f69ac421ea76259f31c8dbed0/pixel.png
2024-07-14 15:28:25 - django.server - WARNING - "GET /track/7e8d1d0f69ac421ea76259f31c8dbed0/pixel.png HTTP/1.1" 404 9
2024-07-14 15:28:25 - django.server - INFO - "GET /serve-image/logo.png/ HTTP/1.1" 200 17485
2024-07-14 15:31:35 - tracking.views - INFO - Sending email to testing@testing.com. Process ID: 68094, Thread ID: 137578913199680
2024-07-14 15:31:35 - tracking.email_utils - INFO - email_utils.py: Email db entry created for testing@testing.com at 2024-07-14 10:01:35.193530+00:00
2024-07-14 15:31:35 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to testing@testing.com
2024-07-14 15:31:35 - django.server - INFO - "POST /send-tracked-email/ HTTP/1.1" 200 2252
2024-07-14 15:31:35 - django.request - WARNING - Not Found: /favicon.ico
2024-07-14 15:31:48 - tracking.urls - INFO - urls.py: PIXEL Request received for email testing@testing.com from ip: 127.0.0.1
2024-07-14 15:31:48 - tracking.views - INFO - View2 called. Process ID: 68094, Thread ID: 137578913199680
2024-07-14 15:31:48 - tracking.views - INFO - views.py/handle_tracking: PrefetchCheck - Current time: 2024-07-14 10:01:48.608072+00:00 | Mail sent: 2024-07-14 10:01:35.153478+00:00 | Difference: 0:00:13.454594
2024-07-14 15:31:48 - django.server - INFO - "GET /serve-image/logo.png/ HTTP/1.1" 200 17485
2024-07-14 15:31:48 - django.server - INFO - "GET /track/2049a1862db3455c895d4ae78e4afbaf/pixel.png HTTP/1.1" 200 114
2024-07-14 15:34:38 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-14 15:34:39 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 15:35:42 - tracking.views - INFO - Sending email to test@logo.com. Process ID: 69849, Thread ID: 127593565124160
2024-07-14 15:35:42 - tracking.email_utils - INFO - email_utils.py: Email db entry created for test@logo.com at 2024-07-14 10:05:42.706109+00:00
2024-07-14 15:35:42 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to test@logo.com
2024-07-14 15:35:42 - django.server - INFO - "POST /send-tracked-email/ HTTP/1.1" 200 2252
2024-07-14 15:36:03 - tracking.urls - INFO - urls.py: PIXEL Request received for email test@logo.com from ip: 127.0.0.1
2024-07-14 15:36:03 - tracking.views - INFO - View2 called. Process ID: 69849, Thread ID: 127593556731456
2024-07-14 15:36:03 - tracking.views - INFO - views.py/handle_tracking: PrefetchCheck - Current time: 2024-07-14 10:06:03.007620+00:00 | Mail sent: 2024-07-14 10:05:42.674000+00:00 | Difference: 0:00:20.333620
2024-07-14 15:36:03 - django.server - INFO - "GET /track/842bd45bcbad4674b6fc6c37665e0a95/pixel.png HTTP/1.1" 200 114
2024-07-14 15:36:03 - django.server - ERROR - "GET /serve-image/logo.png/ HTTP/1.1" 500 59
2024-07-14 15:36:08 - tracking.urls - INFO - urls.py: PIXEL Request received for email test@logo.com from ip: 127.0.0.1
2024-07-14 15:36:08 - tracking.views - INFO - View2 called. Process ID: 69849, Thread ID: 127593344923200
2024-07-14 15:36:08 - tracking.views - INFO - views.py/handle_tracking: PrefetchCheck - Current time: 2024-07-14 10:06:08.874928+00:00 | Mail sent: 2024-07-14 10:05:42.674000+00:00 | Difference: 0:00:26.200928
2024-07-14 15:36:08 - tracking.views - INFO - views.py/handle_tracking: MultihitCheck - Current time: 2024-07-14 10:06:08.874928+00:00 | last_log time: 2024-07-14 10:06:03.009034+00:00 | Difference: 0:00:05.865894
2024-07-14 15:36:08 - django.server - INFO - "GET /track/842bd45bcbad4674b6fc6c37665e0a95/pixel.png HTTP/1.1" 200 114
2024-07-14 15:36:08 - django.server - ERROR - "GET /serve-image/logo.png/ HTTP/1.1" 500 59
2024-07-14 15:36:27 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-14 15:36:28 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 15:36:40 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 15:36:47 - tracking.views - INFO - Sending email to test@logo.com. Process ID: 70218, Thread ID: 138771234289216
2024-07-14 15:36:47 - tracking.email_utils - INFO - email_utils.py: Email db entry created for test@logo.com at 2024-07-14 10:06:47.216902+00:00
2024-07-14 15:36:47 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to test@logo.com
2024-07-14 15:36:47 - django.server - INFO - "POST /send-tracked-email/ HTTP/1.1" 200 2252
2024-07-14 15:36:54 - tracking.urls - INFO - urls.py: PIXEL Request received for email test@logo.com from ip: 127.0.0.1
2024-07-14 15:36:54 - tracking.views - INFO - View2 called. Process ID: 70218, Thread ID: 138771225896512
2024-07-14 15:36:54 - tracking.views - INFO - views.py/handle_tracking: PrefetchCheck - Current time: 2024-07-14 10:06:54.218416+00:00 | Mail sent: 2024-07-14 10:06:47.175448+00:00 | Difference: 0:00:07.042968
2024-07-14 15:36:54 - django.server - INFO - "GET /serve-image/logo.png/ HTTP/1.1" 200 7276
2024-07-14 15:36:54 - django.server - INFO - "GET /track/d1b5165aa47b476283f481d342c52c3d/pixel.png HTTP/1.1" 200 114
2024-07-14 15:37:16 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-14 15:37:16 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 15:37:23 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 15:37:32 - tracking.views - INFO - Sending email to test@logo.com. Process ID: 70325, Thread ID: 135718869399104
2024-07-14 15:37:32 - tracking.email_utils - INFO - email_utils.py: Email db entry created for test@logo.com at 2024-07-14 10:07:32.896222+00:00
2024-07-14 15:37:32 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to test@logo.com
2024-07-14 15:37:32 - django.server - INFO - "POST /send-tracked-email/ HTTP/1.1" 200 2252
2024-07-14 15:37:37 - tracking.urls - INFO - urls.py: PIXEL Request received for email test@logo.com from ip: 127.0.0.1
2024-07-14 15:37:37 - tracking.views - INFO - View2 called. Process ID: 70325, Thread ID: 135718861006400
2024-07-14 15:37:37 - tracking.views - INFO - views.py/handle_tracking: PrefetchCheck - Current time: 2024-07-14 10:07:37.201761+00:00 | Mail sent: 2024-07-14 10:07:32.862731+00:00 | Difference: 0:00:04.339030
2024-07-14 15:37:37 - tracking.views - WARNING - views.py/handle_tracking: First request received for test@logo.com with email_id 33 within 5 secs. Potential prefetching. Abandoning request!
2024-07-14 15:37:37 - django.request - WARNING - Not Found: /track/f3e19c651d2a45bbbc669da952568a98/pixel.png
2024-07-14 15:37:37 - django.server - WARNING - "GET /track/f3e19c651d2a45bbbc669da952568a98/pixel.png HTTP/1.1" 404 9
2024-07-14 15:37:37 - django.server - ERROR - "GET /serve-image/logo.png/ HTTP/1.1" 500 59
2024-07-14 15:37:50 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-14 15:37:50 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 15:38:08 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 15:38:13 - tracking.views - INFO - Sending email to test@logo.com. Process ID: 70467, Thread ID: 132469206545984
2024-07-14 15:38:13 - tracking.email_utils - INFO - email_utils.py: Email db entry created for test@logo.com at 2024-07-14 10:08:13.179213+00:00
2024-07-14 15:38:13 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to test@logo.com
2024-07-14 15:38:13 - django.server - INFO - "POST /send-tracked-email/ HTTP/1.1" 200 2252
2024-07-14 15:38:17 - django.server - ERROR - "GET /serve-image/logo.png/ HTTP/1.1" 500 59
2024-07-14 15:38:17 - tracking.urls - INFO - urls.py: PIXEL Request received for email test@logo.com from ip: 127.0.0.1
2024-07-14 15:38:17 - tracking.views - INFO - View2 called. Process ID: 70467, Thread ID: 132469198153280
2024-07-14 15:38:17 - tracking.views - INFO - views.py/handle_tracking: PrefetchCheck - Current time: 2024-07-14 10:08:17.223645+00:00 | Mail sent: 2024-07-14 10:08:13.139174+00:00 | Difference: 0:00:04.084471
2024-07-14 15:38:17 - tracking.views - WARNING - views.py/handle_tracking: First request received for test@logo.com with email_id 34 within 5 secs. Potential prefetching. Abandoning request!
2024-07-14 15:38:17 - django.request - WARNING - Not Found: /track/242bb6cce36946a8895cfca7abafa4a1/pixel.png
2024-07-14 15:38:17 - django.server - WARNING - "GET /track/242bb6cce36946a8895cfca7abafa4a1/pixel.png HTTP/1.1" 404 9
2024-07-14 15:39:45 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-14 15:39:46 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 15:40:08 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 15:40:15 - tracking.views - INFO - Sending email to test@logo.com. Process ID: 70831, Thread ID: 135914531583552
2024-07-14 15:40:15 - tracking.email_utils - INFO - email_utils.py: Email db entry created for test@logo.com at 2024-07-14 10:10:15.081534+00:00
2024-07-14 15:40:15 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to test@logo.com
2024-07-14 15:40:15 - django.server - INFO - "POST /send-tracked-email/ HTTP/1.1" 200 2252
2024-07-14 15:40:19 - django.server - INFO - "GET /serve-image/logo.png/ HTTP/1.1" 200 7276
2024-07-14 15:40:19 - tracking.urls - INFO - urls.py: PIXEL Request received for email test@logo.com from ip: 127.0.0.1
2024-07-14 15:40:19 - tracking.views - INFO - View2 called. Process ID: 70831, Thread ID: 135914523190848
2024-07-14 15:40:19 - tracking.views - INFO - views.py/handle_tracking: PrefetchCheck - Current time: 2024-07-14 10:10:19.366127+00:00 | Mail sent: 2024-07-14 10:10:15.048497+00:00 | Difference: 0:00:04.317630
2024-07-14 15:40:19 - tracking.views - WARNING - views.py/handle_tracking: First request received for test@logo.com with email_id 35 within 5 secs. Potential prefetching. Abandoning request!
2024-07-14 15:40:19 - django.request - WARNING - Not Found: /track/93687a44eec648de809393a855c90c4a/pixel.png
2024-07-14 15:40:19 - django.server - WARNING - "GET /track/93687a44eec648de809393a855c90c4a/pixel.png HTTP/1.1" 404 9
2024-07-14 15:40:30 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-14 15:40:30 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 15:40:40 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 15:40:43 - tracking.views - INFO - Sending email to test@logo.com. Process ID: 70927, Thread ID: 126425759741504
2024-07-14 15:40:43 - tracking.email_utils - INFO - email_utils.py: Email db entry created for test@logo.com at 2024-07-14 10:10:43.928173+00:00
2024-07-14 15:40:43 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to test@logo.com
2024-07-14 15:40:43 - django.server - INFO - "POST /send-tracked-email/ HTTP/1.1" 200 2252
2024-07-14 15:40:51 - tracking.urls - INFO - urls.py: PIXEL Request received for email test@logo.com from ip: 127.0.0.1
2024-07-14 15:40:51 - tracking.views - INFO - View2 called. Process ID: 70927, Thread ID: 126425751348800
2024-07-14 15:40:51 - tracking.views - INFO - views.py/handle_tracking: PrefetchCheck - Current time: 2024-07-14 10:10:51.872427+00:00 | Mail sent: 2024-07-14 10:10:43.893430+00:00 | Difference: 0:00:07.978997
2024-07-14 15:40:51 - django.server - INFO - "GET /serve-image/logo.png/ HTTP/1.1" 200 7276
2024-07-14 15:40:51 - django.server - INFO - "GET /track/8e1a0bba6c4440f59b60738fe03f833a/pixel.png HTTP/1.1" 200 114
2024-07-14 15:41:43 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-14 15:41:43 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 15:45:02 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-14 15:45:03 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 15:45:08 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-14 15:45:08 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 15:52:12 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/email_tracker/settings.py changed, reloading.
2024-07-14 15:52:13 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 17:46:10 - django.server - INFO - "GET /dashboard/ HTTP/1.1" 200 26899
2024-07-14 17:46:10 - django.request - WARNING - Not Found: /favicon.ico
2024-07-14 17:49:21 - tracking.urls - INFO - urls.py: PIXEL Request received for email test@logo.com from ip: 127.0.0.1
2024-07-14 17:49:21 - tracking.views - INFO - View2 called. Process ID: 73029, Thread ID: 140395887457856
2024-07-14 17:49:21 - tracking.views - INFO - views.py/handle_tracking: PrefetchCheck - Current time: 2024-07-14 12:19:21.618350+00:00 | Mail sent: 2024-07-14 10:10:43.893430+00:00 | Difference: 2:08:37.724920
2024-07-14 17:49:21 - tracking.views - INFO - views.py/handle_tracking: MultihitCheck - Current time: 2024-07-14 12:19:21.618350+00:00 | last_log time: 2024-07-14 10:10:51.874143+00:00 | Difference: 2:08:29.744207
2024-07-14 17:49:21 - django.server - INFO - "GET /serve-image/logo.png/ HTTP/1.1" 200 7276
2024-07-14 17:49:21 - django.server - INFO - "GET /track/8e1a0bba6c4440f59b60738fe03f833a/pixel.png HTTP/1.1" 200 114
2024-07-14 17:49:40 - tracking.views - INFO - Sending email to anot@anot.com. Process ID: 73029, Thread ID: 140395887457856
2024-07-14 17:49:40 - tracking.email_utils - INFO - email_utils.py: Email db entry created for anot@anot.com at 2024-07-14 12:19:40.838651+00:00
2024-07-14 17:49:40 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to anot@anot.com
2024-07-14 17:49:40 - django.server - INFO - "POST /send-tracked-email/ HTTP/1.1" 200 2252
2024-07-14 17:49:47 - tracking.urls - INFO - urls.py: PIXEL Request received for email anot@anot.com from ip: 127.0.0.1
2024-07-14 17:49:47 - tracking.views - INFO - View2 called. Process ID: 73029, Thread ID: 140395879065152
2024-07-14 17:49:47 - tracking.views - INFO - views.py/handle_tracking: PrefetchCheck - Current time: 2024-07-14 12:19:47.339670+00:00 | Mail sent: 2024-07-14 12:19:40.811315+00:00 | Difference: 0:00:06.528355
2024-07-14 17:49:47 - django.server - INFO - "GET /track/5bf7b9fd3aa34b5780f8d2c64d99b953/pixel.png HTTP/1.1" 200 114
2024-07-14 17:49:47 - django.server - INFO - "GET /serve-image/logo.png/ HTTP/1.1" 200 7276
2024-07-14 17:49:51 - django.request - ERROR - Internal Server Error: /track-link/16/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-14 17:49:51 - django.server - ERROR - "GET /track-link/16/ HTTP/1.1" 500 145
2024-07-14 17:55:04 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-14 17:55:04 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 17:55:19 - tracking.urls - INFO - urls.py: PIXEL Request received for email anot@anot.com from ip: 127.0.0.1
2024-07-14 17:55:19 - tracking.views - INFO - View2 called. Process ID: 93016, Thread ID: 124657529255488
2024-07-14 17:55:19 - tracking.views - INFO - views.py/handle_tracking: PrefetchCheck - Current time: 2024-07-14 12:25:19.431953+00:00 | Mail sent: 2024-07-14 12:19:40.811315+00:00 | Difference: 0:05:38.620638
2024-07-14 17:55:19 - tracking.views - INFO - views.py/handle_tracking: MultihitCheck - Current time: 2024-07-14 12:25:19.431953+00:00 | last_log time: 2024-07-14 12:19:47.340650+00:00 | Difference: 0:05:32.091303
2024-07-14 17:55:19 - django.server - INFO - "GET /track/5bf7b9fd3aa34b5780f8d2c64d99b953/pixel.png HTTP/1.1" 200 114
2024-07-14 17:55:19 - django.server - INFO - "GET /serve-image/logo.png/ HTTP/1.1" 200 7276
2024-07-14 17:55:20 - django.request - ERROR - Internal Server Error: /track-link/16/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-14 17:55:20 - django.server - ERROR - "GET /track-link/16/ HTTP/1.1" 500 145
2024-07-14 17:56:38 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-14 17:56:38 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 17:56:44 - django.request - ERROR - Internal Server Error: /track-link/16/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: log_request_link.<locals>.wrapper() missing 1 required positional argument: 'token'
2024-07-14 17:56:44 - django.server - ERROR - "GET /track-link/16/ HTTP/1.1" 500 145
2024-07-14 17:59:43 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-14 17:59:43 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 18:05:03 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/urls.py changed, reloading.
2024-07-14 18:05:03 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 18:05:19 - django.request - ERROR - Internal Server Error: /track-link/16/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/urls.py", line 33, in wrapper
    recipient = TrackingPixelToken.objects.get(token=token).email.recipient
NameError: name 'token' is not defined
2024-07-14 18:05:19 - django.server - ERROR - "GET /track-link/16/ HTTP/1.1" 500 145
2024-07-14 18:07:36 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/urls.py changed, reloading.
2024-07-14 18:07:37 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 18:10:26 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/urls.py changed, reloading.
2024-07-14 18:10:26 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 18:10:49 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/urls.py changed, reloading.
2024-07-14 18:10:49 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 18:11:07 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/urls.py changed, reloading.
2024-07-14 18:11:07 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 18:11:12 - tracking.urls - INFO - urls.py: LINK Request received for email anot@anot.com from ip: 127.0.0.1
2024-07-14 18:11:12 - django.server - INFO - "GET /track-link/16/ HTTP/1.1" 302 0
2024-07-14 18:50:35 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-14 18:50:35 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 18:51:15 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-14 18:51:15 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-14 18:51:51 - tracking.urls - INFO - urls.py: PIXEL Request received for email test@logo.com from ip: 127.0.0.1
2024-07-14 18:51:51 - tracking.views - INFO - View2 called. Process ID: 105946, Thread ID: 124618513839680
2024-07-14 18:51:51 - tracking.views - INFO - views.py/handle_tracking: PrefetchCheck - Current time: 2024-07-14 13:21:51.182943+00:00 | Mail sent: 2024-07-14 10:10:43.893430+00:00 | Difference: 3:11:07.289513
2024-07-14 18:51:51 - tracking.views - INFO - views.py/handle_tracking: MultihitCheck - Current time: 2024-07-14 13:21:51.182943+00:00 | last_log time: 2024-07-14 12:19:21.619948+00:00 | Difference: 1:02:29.562995
2024-07-14 18:51:51 - django.server - INFO - "GET /serve-image/logo.png/ HTTP/1.1" 200 7276
2024-07-14 18:51:51 - django.server - INFO - "GET /track/8e1a0bba6c4440f59b60738fe03f833a/pixel.png HTTP/1.1" 200 95
2024-07-14 18:52:03 - django.server - INFO - "GET /dashboard/ HTTP/1.1" 200 30338
2024-07-14 18:52:03 - django.request - WARNING - Not Found: /favicon.ico
2024-07-14 18:52:10 - tracking.urls - INFO - urls.py: PIXEL Request received for email anot@anot.com from ip: 127.0.0.1
2024-07-14 18:52:10 - tracking.views - INFO - View2 called. Process ID: 105946, Thread ID: 124618505446976
2024-07-14 18:52:10 - tracking.views - INFO - views.py/handle_tracking: PrefetchCheck - Current time: 2024-07-14 13:22:10.895523+00:00 | Mail sent: 2024-07-14 12:19:40.811315+00:00 | Difference: 1:02:30.084208
2024-07-14 18:52:10 - tracking.views - INFO - views.py/handle_tracking: MultihitCheck - Current time: 2024-07-14 13:22:10.895523+00:00 | last_log time: 2024-07-14 12:25:19.433367+00:00 | Difference: 0:56:51.462156
2024-07-14 18:52:10 - django.server - INFO - "GET /serve-image/logo.png/ HTTP/1.1" 200 7276
2024-07-14 18:52:10 - django.server - INFO - "GET /track/5bf7b9fd3aa34b5780f8d2c64d99b953/pixel.png HTTP/1.1" 200 95
2024-07-14 18:52:17 - django.server - INFO - "GET /dashboard/ HTTP/1.1" 200 30932
2024-07-15 10:54:43 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-15 10:54:47 - django.request - WARNING - Not Found: /favicon.ico
2024-07-15 10:54:47 - django.server - WARNING - "GET /favicon.ico HTTP/1.1" 404 179
2024-07-15 10:54:48 - django.request - ERROR - Internal Server Error: /send-mailgun-mail/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py", line 48, in send_mailgun_mail_view
    for recip in [recipient_list[-3]]:
IndexError: list index out of range
2024-07-15 10:54:52 - django.request - ERROR - Internal Server Error: /send-mailgun-mail/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py", line 48, in send_mailgun_mail_view
    for recip in [recipient_list[-3]]:
IndexError: list index out of range
2024-07-15 10:54:52 - django.server - ERROR - "GET /send-mailgun-mail/ HTTP/1.1" 500 145
2024-07-15 10:54:52 - django.request - WARNING - Not Found: /favicon.ico
2024-07-15 10:55:08 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-15 10:55:08 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-15 10:55:10 - django.request - ERROR - Internal Server Error: /send-mailgun-mail/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py", line 50, in send_mailgun_mail_view
    response = send_simple_message(subject, message, from_email, recip)
  File "/home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/mailgun_utils.py", line 30, in send_simple_message
    auth=("api", settings.MAILGUN_API_KEY),
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/conf/__init__.py", line 91, in __getattr__
    val = getattr(_wrapped, name)
AttributeError: 'Settings' object has no attribute 'MAILGUN_API_KEY'
2024-07-15 10:55:10 - django.server - ERROR - "GET /send-mailgun-mail/ HTTP/1.1" 500 145
2024-07-15 10:56:16 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-15 10:56:23 - django.server - INFO - "GET /send-mailgun-mail/ HTTP/1.1" 200 24
2024-07-15 11:10:21 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-15 11:10:21 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-15 11:10:28 - django.server - INFO - "GET /send-mailgun-mail/ HTTP/1.1" 200 24
2024-07-15 11:10:28 - django.request - WARNING - Not Found: /favicon.ico
2024-07-15 11:59:05 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/mailgun_utils.py changed, reloading.
2024-07-15 11:59:06 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-15 12:00:13 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/mailgun_utils.py changed, reloading.
2024-07-15 12:00:13 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-15 12:01:07 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-15 12:01:07 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-15 12:01:40 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-15 12:01:41 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-15 12:01:43 - django.request - ERROR - Internal Server Error: /send-mailgun-mail/
Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rahul/anaconda3/envs/trackerRENDER/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py", line 52, in send_mailgun_mail_view
    if response.status_code == 200:
UnboundLocalError: local variable 'response' referenced before assignment
2024-07-15 12:01:43 - django.server - ERROR - "GET /send-mailgun-mail/ HTTP/1.1" 500 145
2024-07-15 12:01:43 - django.request - WARNING - Not Found: /favicon.ico
2024-07-15 12:01:58 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-15 12:01:58 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-15 12:02:01 - django.server - INFO - "GET /send-mailgun-mail/ HTTP/1.1" 200 24
2024-07-15 12:11:11 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/mailgun_utils.py changed, reloading.
2024-07-15 12:11:12 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-15 12:11:45 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-15 12:11:45 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-15 12:12:08 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/views.py changed, reloading.
2024-07-15 12:12:09 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-15 12:12:18 - django.server - INFO - "GET /send-mailgun-mail/ HTTP/1.1" 200 24
2024-07-15 12:12:18 - django.request - WARNING - Not Found: /favicon.ico
2024-07-15 18:10:34 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/email_tracker/settings.py changed, reloading.
2024-07-15 18:10:34 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-15 18:11:06 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/email_tracker/settings.py changed, reloading.
2024-07-15 18:11:06 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-15 18:16:59 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/email_tracker/settings.py changed, reloading.
2024-07-15 18:17:00 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-15 18:17:05 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/email_tracker/settings.py changed, reloading.
2024-07-15 18:17:05 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-15 18:17:08 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/email_tracker/settings.py changed, reloading.
2024-07-15 18:17:09 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-15 18:17:32 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/email_tracker/settings.py changed, reloading.
2024-07-15 18:17:32 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-15 18:17:40 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/email_tracker/settings.py changed, reloading.
2024-07-15 18:17:41 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-15 18:26:47 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-15 18:27:20 - tracking.views - INFO - Sending email to 1chandailrc1@gmail.com. Process ID: 81559, Thread ID: 135860309718592
2024-07-15 18:27:20 - tracking.email_utils - INFO - email_utils.py: Email db entry created for 1chandailrc1@gmail.com at 2024-07-15 12:57:20.561499+00:00
2024-07-15 18:27:27 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to 1chandailrc1@gmail.com
2024-07-15 18:27:27 - django.server - INFO - "POST /send-tracked-email/ HTTP/1.1" 200 2252
2024-07-15 18:27:27 - django.request - WARNING - Not Found: /favicon.ico
2024-07-15 18:40:14 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-15 18:40:22 - django.server - INFO - "GET /dashboard/ HTTP/1.1" 200 31467
2024-07-15 18:40:39 - tracking.views - INFO - Sending email to 1chandailrc1@gmail.com. Process ID: 84676, Thread ID: 138414814918208
2024-07-15 18:40:39 - tracking.email_utils - INFO - email_utils.py: Email db entry created for 1chandailrc1@gmail.com at 2024-07-15 13:10:39.524555+00:00
2024-07-15 18:40:44 - tracking.email_utils - ERROR - email_utils.py: Error sending email to 1chandailrc1@gmail.com: (535, b'Authentication credentials invalid')
2024-07-15 18:40:44 - django.server - INFO - "POST /send-tracked-email/ HTTP/1.1" 200 2252
2024-07-15 18:40:59 - tracking.views - INFO - Sending email to 1chandailrc1@gmail.com. Process ID: 84676, Thread ID: 138414814918208
2024-07-15 18:40:59 - tracking.email_utils - INFO - email_utils.py: Email db entry created for 1chandailrc1@gmail.com at 2024-07-15 13:10:59.105473+00:00
2024-07-15 18:41:03 - tracking.email_utils - ERROR - email_utils.py: Error sending email to 1chandailrc1@gmail.com: (535, b'Authentication credentials invalid')
2024-07-15 18:41:03 - django.server - INFO - "POST /send-tracked-email/ HTTP/1.1" 200 2252
2024-07-15 18:41:07 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-15 18:41:12 - tracking.views - INFO - Sending email to 1chandailrc1@gmail.com. Process ID: 84872, Thread ID: 129595739207232
2024-07-15 18:41:12 - tracking.email_utils - INFO - email_utils.py: Email db entry created for 1chandailrc1@gmail.com at 2024-07-15 13:11:12.401228+00:00
2024-07-15 18:41:18 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to 1chandailrc1@gmail.com
2024-07-15 18:41:18 - django.server - INFO - "POST /send-tracked-email/ HTTP/1.1" 200 2252
2024-07-15 18:44:07 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/email_tracker/settings.py changed, reloading.
2024-07-15 18:44:07 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-15 18:44:20 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-15 18:44:34 - tracking.views - INFO - Sending email to 1chandailrc1@gmail.com. Process ID: 85513, Thread ID: 134444029572672
2024-07-15 18:44:34 - tracking.email_utils - INFO - email_utils.py: Email db entry created for 1chandailrc1@gmail.com at 2024-07-15 13:14:34.548201+00:00
2024-07-15 18:44:45 - tracking.email_utils - ERROR - email_utils.py: Error sending email to 1chandailrc1@gmail.com: Connection unexpectedly closed
2024-07-15 18:44:45 - django.server - INFO - "POST /send-tracked-email/ HTTP/1.1" 200 2252
2024-07-15 18:46:43 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/email_tracker/settings.py changed, reloading.
2024-07-15 18:46:44 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-15 18:46:49 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/email_tracker/settings.py changed, reloading.
2024-07-15 18:46:49 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-15 18:48:08 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/email_tracker/settings.py changed, reloading.
2024-07-15 18:48:08 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-15 18:48:13 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/email_tracker/settings.py changed, reloading.
2024-07-15 18:48:13 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-15 18:48:53 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/email_tracker/settings.py changed, reloading.
2024-07-15 18:48:53 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-15 18:48:56 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-15 18:49:07 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-15 18:49:19 - django.server - INFO - "GET /send-tracked-email/ HTTP/1.1" 200 2174
2024-07-15 18:49:19 - django.server - INFO - "GET /send-tracked-email/ HTTP/1.1" 200 2174
2024-07-15 18:49:20 - django.server - INFO - "GET /compose/ HTTP/1.1" 200 2174
2024-07-15 18:49:34 - tracking.views - INFO - Sending email to chandailrc@gmail.com. Process ID: 86673, Thread ID: 130752423392832
2024-07-15 18:49:34 - tracking.email_utils - INFO - email_utils.py: Email db entry created for chandailrc@gmail.com at 2024-07-15 13:19:34.487849+00:00
2024-07-15 18:49:38 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to chandailrc@gmail.com
2024-07-15 18:49:38 - django.server - INFO - "POST /send-tracked-email/ HTTP/1.1" 200 2252
2024-07-15 18:49:38 - django.request - WARNING - Not Found: /favicon.ico
2024-07-15 19:54:17 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/email_tracker/settings.py changed, reloading.
2024-07-15 19:54:17 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-15 20:06:56 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-15 20:07:21 - tracking.views - INFO - Sending email to chandailrc@gmail.com. Process ID: 99947, Thread ID: 123888813995584
2024-07-15 20:07:22 - tracking.email_utils - INFO - email_utils.py: Email db entry created for chandailrc@gmail.com at 2024-07-15 14:37:22.039261+00:00
2024-07-15 20:07:27 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to chandailrc@gmail.com
2024-07-15 20:07:27 - django.server - INFO - "POST /send-tracked-email/ HTTP/1.1" 200 2252
2024-07-15 20:07:27 - django.request - WARNING - Not Found: /favicon.ico
2024-07-15 20:58:38 - tracking.views - INFO - Sending email to testing@test.com. Process ID: 99947, Thread ID: 123888813995584
2024-07-15 20:58:38 - tracking.email_utils - INFO - email_utils.py: Email db entry created for testing@test.com at 2024-07-15 15:28:38.356940+00:00
2024-07-15 20:58:44 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to testing@test.com
2024-07-15 20:58:44 - django.server - INFO - "POST /send-tracked-email/ HTTP/1.1" 200 2252
2024-07-15 20:59:00 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-15 20:59:04 - tracking.views - INFO - Sending email to testing@test.com. Process ID: 109560, Thread ID: 134842545075776
2024-07-15 20:59:04 - tracking.email_utils - INFO - email_utils.py: Email db entry created for testing@test.com at 2024-07-15 15:29:04.211711+00:00
2024-07-15 20:59:04 - tracking.email_utils - INFO - email_utils.py: Email sent successfully to testing@test.com
2024-07-15 20:59:04 - django.server - INFO - "POST /send-tracked-email/ HTTP/1.1" 200 2252
2024-07-15 20:59:09 - django.server - INFO - "GET /serve-image/logo.png HTTP/1.1" 301 0
2024-07-15 20:59:09 - tracking.urls - INFO - urls.py: PIXEL Request received for email testing@test.com from ip: 127.0.0.1
2024-07-15 20:59:09 - tracking.views - INFO - View2 called. Process ID: 109560, Thread ID: 134842536683072
2024-07-15 20:59:09 - tracking.views - INFO - views.py/handle_tracking: PrefetchCheck - Current time: 2024-07-15 15:29:09.969020+00:00 | Mail sent: 2024-07-15 15:29:04.173136+00:00 | Difference: 0:00:05.795884
2024-07-15 20:59:10 - django.server - INFO - "GET /serve-image/logo.png/ HTTP/1.1" 200 7276
2024-07-15 20:59:10 - django.server - INFO - "GET /track/5b832ada9257433ca73a74eeb5e31d11/pixel.png HTTP/1.1" 200 95
2024-07-15 21:11:04 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/email_utils.py changed, reloading.
2024-07-15 21:11:04 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-15 22:12:24 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/email_utils.py changed, reloading.
2024-07-15 22:12:24 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-15 22:20:14 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/email_utils.py changed, reloading.
2024-07-15 22:20:14 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-07-15 22:40:15 - django.utils.autoreload - INFO - /home/rahul/conda_ws/django_ws/email_tracker_barebones/email_tracker_RENDER/tracking/email_utils.py changed, reloading.
2024-07-15 22:40:16 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
